### ISSUE TITLE
Make it possible to rate maps

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aoe2map#10]
The easiest and most robust solution would possibly be the option to give maps a thumbs-up :+1: 
(Do we also want to have a thumbs-down? Discuss.)

**Comment by HenkDeSuperNerd** [comment]
thumbs up or number of downloads seems like a good way to show the popularity of maps

**Comment by HSZemi** [comment]
Hearts are implemented. Number of downloads is not easily doable with the way it is currently hosted, since it's the regular webserver that serves the rms files. Let's close this until somebody *needs* a more elaborate solution.
