### ISSUE TITLE
Version number in map download file path.

### ISSUE THREAD

**Issue by Jabark** [SiegeEngineers/aoe2map#22]
Make maps download with the version number to avoid players getting conflicts.

**Comment by HSZemi** [comment]
Possible issues with this approach:
- The map might already have the version number in the file name, leading to stuff like `ForestNothing_v1_v1.rms`
- The map might already have a different version number in the file name, leading to stuff like `ForestNothing_v1_1.0.rms` or `ForestNothing-1.0.0_v3.2.rms`
- It makes the map name longer in-game

Our current philosophy is to only touch user generated data where necessary (e.g. rescaling uploaded images), but we usually keep file contents and names as they are, so I would advocate agains such a feature currently.
