### ISSUE TITLE
Search for Names Containing Underscores

### ISSUE THREAD

**Issue by twestura** [SiegeEngineers/aoe2map#24]
I have a map named "Arabia_Bamboo": https://aoe2map.net/map/e541d3c8-a342-41b2-8135-8dbea53728d0

Using the website's search functionality, search for "Arabia Bamboo" (with a space, not an underscore). No results are returned.
A search for just "Bamboo" or for "Arabia_Bamboo" with an underscore returns the map in the results.

It would be nice if the search functionality could support searching for maps that use various word separators, e.g. spaces ` `, underscores `_`, and dashes `-`, as I was expecting the map to be returned with those searches.

**Comment by HSZemi** [comment]
I hope [19.8.4](https://github.com/SiegeEngineers/aoe2map/releases/tag/19.8.4) meets your wishes :yellow_heart:
